name: Deploy Docs Azure Static Web App

on:
  push:
    branches:
      - 💥
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - 💥

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run docs:build
      - name: PostProcess
        run: dotnet fsi src/.vuepress/postprocess.fsx
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0E422DD00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./src/.vuepress/dist" # App source code path
          output_location: "./src/.vuepress/dist"
          app_artifact_location: "./src/.vuepress/dist" 
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0E422DD00 }}
          action: "close"
          app_location: "/" 
